FROM python
# python is name of docker image from docker HUB 
RUN  mkdir /ashu-code 
# running given instruction to above image 
COPY  hello.py  /ashu-code/hello.py 
# copy code from current location to docker image 
CMD  ["python" ,"/ashu-code/hello.py"] 
# this will be default process of container by this image 
