apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ashupod1
  name: ashupod1
spec:
  imagePullSecrets:
  - name: ashu-acr-creds
  containers:
  - image: rocheashutoshh.azurecr.io/ashuwebapp:v1
    name: ashupod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
